name: Feature Request
description: Suggest a new feature
title: "[FEATURE] "
labels: ["enhancement"]

body:
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Why is this needed?